### ISSUE TITLE
Create landing page.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/My-Website#1]
**Motivation**

Create a landing page so a user knows who the page is about. (Me!)

**Tasks**

- [x] Structure File System
- [x] Create background image.
- [x] Add links to button elements.
- [x] Style elements to my liking.
- [x] Render elements in React.

**Comment by anthonyrodarte** [comment]
Removed Bootstrap Cover theme due to interference with the rest of the website. Will re-write landing page by hand instead.
